config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get "/about" => "static_pages#about"
  get "/signup" => "users#new"
  post "/signup" => "users#create"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
 
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #successful save
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="footer-logo">
      <%=link_to "VoiceCoding", root_path %>
    </div>
    <div class="footer-list">
      <p>作成者：今村圭佑</p>
      <p>メールアドレス：taicho.nv@gmail.com</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="header-logo">
      <%= link_to "VoiceCoding", root_path, class:"header-link" %>
    </div>
    <div class="header-list">
      <ul>
        <li><%= link_to "概要", about_path, class:"header-link" %></li>
        <li><%= link_to "サインアップ", signup_path, class:"header-link" %></li>
        <li><%= link_to "サインイン", "#", class:"header-link" %></li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoiceCoding</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render "layouts/header" %>
    <%= yield %>
    <%=render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="about">
  <div class="about-inner">
    <div class="container">
      <div class="about-wrapper">
        <div class="about-box">
          <div class="about-title">
            About
          </div>
          <div class="about-sentence">
            名前のとおり、音声の入力のみでコーディングを行う。<br>
            VoiceCodingは手入力以外の入力により、プログラムがかけたらいいなという希望から開発が始まった。<br>
          </div>
        </div>

        <div class="about-box">
          <div class="about-title">
            Ideal
          </div>
          <div class="about-sentence">
            人間はひとつの事柄を様々な言葉で表現することができる。<br>
            よって、人によって音声入力の仕方は様々であることは自明である。<br>
            どのような表現でも同じ意味と認識させ、プログラミングができればいいと思っている。<br>
            また、プログラム入力中にAIと会話することで、他者と一緒にプログラミングを
            しているようになったら面白いんじゃないかと思う。
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="home">
  <div class="home-inner">
    <div class="container">
      <div class="home-wrapper">
        <div class="home-logo">VoiceCoding</div>
        <div class="home-sub">キーボードのないコーディングを体験しよう</div>
        <div class="signup_btn">
          <input type="button" value="サインアップ" onClick="location.href='<%=signup_path%>'"  class="btn btn-primary">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="signup">
  <div class="signup-inner">
    <div class="container">
      <div class="signup-wrapper">
        <div class="signup-title">
          Sign Up
        </div>
        <div class="signup-form">
          <%= form_for(@user, url: signup_path) do |f| %>
          <%= render "shared/error_message" %>

          <%= f.text_field :name, :placeholder=>"Name" %><br>

          <%= f.text_field :email, :placeholder=>"Email" %><br>

          <%= f.text_field :password, :placeholder=>"Password" %><br>

          <%= f.text_field :password_confirmation, :placeholder=>"Confirmation" %><br>

          <%= f.submit "Create my account", class:"signup-submit", :value=>"Submit" %><br>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user">
  <%= @user.name %>, <%= @user.email %>
</div>